{
    "name": "Compassion Theme 2025",
    "category": "Theme/Compassion",
    "summary": "Compassion Theme 2025",
    "website": "https://github.com/CompassionCH/compassion-website",
    "sequence": 260,
    "version": "14.0.1.0.0",
    "author": "Compassion Switzerland",
    "depends": ["website"],
    "data": [
        "views/assets.xml",
        "views/images_content.xml",
        "views/template_header.xml",
        # Buttons
        "templates/components/buttons/ThemedButton.xml",

        # Icons
        "templates/components/icons/Address24.xml",
        "templates/components/icons/AgeBirthday24.xml",
        "templates/components/icons/ArrowDown24.xml",
        "templates/components/icons/ArrowRight24.xml",
        "templates/components/icons/ArrowRightAngle24.xml",
        "templates/components/icons/ArrowUp24.xml",
        "templates/components/icons/Birthday24.xml",
        "templates/components/icons/BoxThreadBlueYellow56.xml",
        "templates/components/icons/ChartFundAllocationBlue.xml",
        "templates/components/icons/ChartFundAllocationBlueWithText.xml",
        "templates/components/icons/ChartFundAllocationGreen.xml",
        "templates/components/icons/ChartFundAllocationGreenTextOnly.xml",
        "templates/components/icons/ChartFundAllocationGreenTextOnlyLarger.xml",
        "templates/components/icons/ChartFundAllocationGreenWithText.xml",
        "templates/components/icons/ChartFundAllocationGreenWithTextLarger.xml",
        "templates/components/icons/Chat24.xml",
        "templates/components/icons/Chat56.xml",
        "templates/components/icons/ChildProfileBirthday42.xml",
        "templates/components/icons/ChildProfileClose48.xml",
        "templates/components/icons/ChildProfileEducation42.xml",
        "templates/components/icons/ChildProfileHobbies42.xml",
        "templates/components/icons/ChildProfileLocationMapPin48.xml",
        "templates/components/icons/ChildResults24.xml",
        "templates/components/icons/Close24.xml",
        "templates/components/icons/Close36.xml",
        "templates/components/icons/CompletedTick32.xml",
        "templates/components/icons/ContactAddress24.xml",
        "templates/components/icons/ContactEmail24.xml",
        "templates/components/icons/ContactPhone24.xml",
        "templates/components/icons/Country24.xml",
        "templates/components/icons/Download24.xml",
        "templates/components/icons/Email24.xml",
        "templates/components/icons/Email56.xml",
        "templates/components/icons/Error24.xml",
        "templates/components/icons/Female24.xml",
        "templates/components/icons/FivePoundRoundUp.xml",
        "templates/components/icons/FormDropdownArrow.xml",
        "templates/components/icons/FormSelect24.xml",
        "templates/components/icons/HamburgerMenu36.xml",
        "templates/components/icons/IconPaginationNext24.xml",
        "templates/components/icons/IconPaginationPrevious24.xml",
        "templates/components/icons/IconPlay24.xml",
        "templates/components/icons/IconReadingTime24.xml",
        "templates/components/icons/Information24.xml",
        "templates/components/icons/Male24.xml",
        "templates/components/icons/MenuGivingBasket28.xml",
        "templates/components/icons/PageLeft36.xml",
        "templates/components/icons/PageRight36.xml",
        "templates/components/icons/Phone24.xml",
        "templates/components/icons/Phone56.xml",
        "templates/components/icons/PictogramQuoteClose512w.xml",
        "templates/components/icons/PictogramQuoteOpen512w.xml",
        "templates/components/icons/ProgrammeChildDevelopment48.xml",
        "templates/components/icons/ProgrammeInterventions48.xml",
        "templates/components/icons/ProgrammeMumsAndBabies48.xml",
        "templates/components/icons/QuoteIcon48w.xml",
        "templates/components/icons/Search24.xml",
        "templates/components/icons/SocialFacebook36.xml",
        "templates/components/icons/SocialInstagram36.xml",
        "templates/components/icons/SocialTiktok36.xml",
        "templates/components/icons/SocialYoutube36.xml",
        "templates/components/icons/SolutionsIconProjectLocationPin.xml",
        "templates/components/icons/SponsorshipSelectorCouple.xml",
        "templates/components/icons/SponsorshipSelectorCoupleChosen.xml",
        "templates/components/icons/SponsorshipSelectorFamily.xml",
        "templates/components/icons/SponsorshipSelectorFamilyChosen.xml",
        "templates/components/icons/SponsorshipSelectorGroup.xml",
        "templates/components/icons/SponsorshipSelectorGroupChosen.xml",
        "templates/components/icons/SponsorshipSelectorIndividual.xml",
        "templates/components/icons/SponsorshipSelectorIndividualChosen.xml",
        "templates/components/icons/User24.xml",
        "templates/components/icons/User36.xml",

        # Pictograms
        "templates/components/pictograms/Advocacy.xml",
        "templates/components/pictograms/BibleGift.xml",
        "templates/components/pictograms/BirthdayGift.xml",
        "templates/components/pictograms/BuildingsCity.xml",
        "templates/components/pictograms/BuildingsHouse.xml",
        "templates/components/pictograms/BuildingsNeighbourhood.xml",
        "templates/components/pictograms/BuildingsRural.xml",
        "templates/components/pictograms/CentreGift.xml",
        "templates/components/pictograms/ChildFocused.xml",
        "templates/components/pictograms/ChildSponsorship.xml",
        "templates/components/pictograms/Children.xml",
        "templates/components/pictograms/ChristCentred.xml",
        "templates/components/pictograms/ChristmasGift.xml",
        "templates/components/pictograms/ChurchBased.xml",
        "templates/components/pictograms/CognitiveBrain.xml",
        "templates/components/pictograms/CriticalNeeds.xml",
        "templates/components/pictograms/DisasterRelief.xml",
        "templates/components/pictograms/EducationAndTraining.xml",
        "templates/components/pictograms/Family.xml",
        "templates/components/pictograms/FamilyGift.xml",
        "templates/components/pictograms/Food.xml",
        "templates/components/pictograms/GeneralDonation.xml",
        "templates/components/pictograms/GlobeGlobal.xml",
        "templates/components/pictograms/Health.xml",
        "templates/components/pictograms/HighlyVulnerableChildren.xml",
        "templates/components/pictograms/IncomeGeneration.xml",
        "templates/components/pictograms/Infrastructure.xml",
        "templates/components/pictograms/LetterWriting.xml",
        "templates/components/pictograms/LocalEmpowermentPartnership.xml",
        "templates/components/pictograms/LocationPin.xml",
        "templates/components/pictograms/MothersAndBabies.xml",
        "templates/components/pictograms/Neighbourhood.xml",
        "templates/components/pictograms/Physical.xml",
        "templates/components/pictograms/SocioEmotional.xml",
        "templates/components/pictograms/Spiritual.xml",
        "templates/components/pictograms/UnsponsoredChildren.xml",
        "templates/components/pictograms/Virus.xml",
        "templates/components/pictograms/WaterAndSanitation.xml",
        "templates/components/pictograms/WereMostNeeded.xml"
    ],
    "images": ["static/description/compassion_screenshot.png"],
    "license": "LGPL-3",
}
