{
    "name": "Compassion Theme 2025",
    "category": "Theme/Compassion",
    "summary": "Compassion Theme 2025",
    "website": "https://github.com/CompassionCH/compassion-website",
    "sequence": 260,
    "version": "14.0.1.0.0",
    "author": "Compassion Switzerland",
    "depends": ["website"],
    "data": [
        "views/assets.xml",
        "views/images_content.xml",
        "views/template_header.xml",
        # Buttons
        "templates/components/buttons/ThemedButton.xml",

        # Pictograms
        "templates/components/pictograms/Advocacy.xml",
        "templates/components/pictograms/BibleGift.xml",
        "templates/components/pictograms/BirthdayGift.xml",
        "templates/components/pictograms/BuildingsCity.xml",
        "templates/components/pictograms/BuildingsHouse.xml",
        "templates/components/pictograms/BuildingsNeighbourhood.xml",
        "templates/components/pictograms/BuildingsRural.xml",
        "templates/components/pictograms/CentreGift.xml",
        "templates/components/pictograms/ChildFocused.xml",
        "templates/components/pictograms/ChildSponsorship.xml",
        "templates/components/pictograms/Children.xml",
        "templates/components/pictograms/ChristCentred.xml",
        "templates/components/pictograms/ChristmasGift.xml",
        "templates/components/pictograms/ChurchBased.xml",
        "templates/components/pictograms/CognitiveBrain.xml",
        "templates/components/pictograms/CriticalNeeds.xml",
        "templates/components/pictograms/DisasterRelief.xml",
        "templates/components/pictograms/EducationAndTraining.xml",
        "templates/components/pictograms/Family.xml",
        "templates/components/pictograms/FamilyGift.xml",
        "templates/components/pictograms/Food.xml",
        "templates/components/pictograms/GeneralDonation.xml",
        "templates/components/pictograms/GlobeGlobal.xml",
        "templates/components/pictograms/Health.xml",
        "templates/components/pictograms/HighlyVulnerableChildren.xml",
        "templates/components/pictograms/IncomeGeneration.xml",
        "templates/components/pictograms/Infrastructure.xml",
        "templates/components/pictograms/LetterWriting.xml",
        "templates/components/pictograms/LocalEmpowermentPartnership.xml",
        "templates/components/pictograms/LocationPin.xml",
        "templates/components/pictograms/MothersAndBabies.xml",
        "templates/components/pictograms/Neighbourhood.xml",
        "templates/components/pictograms/Physical.xml",
        "templates/components/pictograms/SocioEmotional.xml",
        "templates/components/pictograms/Spiritual.xml",
        "templates/components/pictograms/UnsponsoredChildren.xml",
        "templates/components/pictograms/Virus.xml",
        "templates/components/pictograms/WaterAndSanitation.xml",
        "templates/components/pictograms/WereMostNeeded.xml"
    ],
    "images": ["static/description/compassion_screenshot.png"],
    "license": "LGPL-3",
}
