##############################################################################
#
#    Copyright (C) 2026 Compassion CH (http://www.compassion.ch)
#    @author: Noe Berdoz <nberdoz@compassion.ch>
#
##############################################################################
"""Tests for the dynamic stylesheet pipeline.

Covers the three ir.attachment-backed SCSS files generated by the
stylesheet_generator_mixin: colors, icons, and pictograms. Also exercises
the post-migration upgrade script (URL rename + idempotency + data preservation).
"""
import os

from odoo.tests import TransactionCase, tagged


@tagged("post_install", "-at_install")
class TestDynamicStylesheets(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.URLS = {
            "colors":     "/theme_compassion_2025/dynamic/colors.scss",
            "icons":      "/theme_compassion_2025/dynamic/icons.scss",
            "pictograms": "/theme_compassion_2025/dynamic/pictograms.scss",
        }
        # Absolute path bypasses Odoo module-path resolution so this test is
        # not coupled to the installed module layout. load_script() accepts
        # absolute paths directly (migration.py:51).
        cls._migration_script_path = os.path.join(
            os.path.dirname(__file__),
            "..",
            "migrations",
            "18.0.1.0.0",
            "post-migration.py",
        )

    def _attachment_for(self, url):
        return self.env["ir.attachment"].search([("url", "=", url)], limit=1)

    def _attachment_text(self, url):
        """Return the text content of the ir.attachment at the given URL.

        Reads ir.attachment.raw (bytes, auto-decoded from filestore or db_datas)
        and decodes to UTF-8. Fails the test if the attachment is absent or empty.
        """
        att = self._attachment_for(url)
        self.assertTrue(att, f"ir.attachment for {url} must exist")
        self.assertTrue(att.raw, f"ir.attachment for {url} must have non-empty content")
        return att.raw.decode("utf-8")

    def test_attachments_populated_on_post_init(self):
        """After install, all 3 dynamic stylesheet attachments are non-empty
        and contain the expected CSS class-name prefixes before any page
        request arrives.
        """
        for label, url in self.URLS.items():
            with self.subTest(label=label, url=url):
                text = self._attachment_text(url)
                expected_prefix = {
                    "colors":     "bg-",
                    "icons":      "icon-",
                    "pictograms": "pictogram-",
                }[label]
                self.assertIn(
                    expected_prefix, text,
                    f"{url} CSS should contain at least one '{expected_prefix}' class",
                )

    def test_color_write_regenerates_attachment(self):
        """ORM write() on a color record triggers regeneration of the colors
        stylesheet, and the new color value appears in the served CSS."""
        color = self.env["theme.compassion.colors"].search([], limit=1)
        self.assertTrue(color, "Test DB must have at least one seeded color")
        new_value = "#ff00ff"  # bright magenta, unlikely to collide with seeded data
        color.write({"color": new_value})
        text = self._attachment_text(self.URLS["colors"])
        self.assertIn(new_value, text)

    def test_color_unlink_regenerates_attachment(self):
        """ORM unlink() on a color record triggers regeneration; the deleted
        color's CSS class name no longer appears in the served stylesheet."""
        new_color = self.env["theme.compassion.colors"].create({
            "name": "Test Magenta For Unlink",
            "color": "#abcdef",
        })
        cls_name = new_color.class_name
        text = self._attachment_text(self.URLS["colors"])
        self.assertIn(cls_name, text, "Newly-created color should appear in stylesheet")
        new_color.unlink()
        text_after = self._attachment_text(self.URLS["colors"])
        self.assertNotIn(cls_name, text_after, "Unlinked color must not remain in stylesheet")

    def test_qweb_cache_cleared_on_regenerate(self):
        """A color write must (a) call env.registry.clear_cache() so the next
        bundle compile picks up the change, and (b) produce CSS that reflects
        the new value.

        The mock wraps the real method so the behavioral assertion below is valid:
        clear_cache() actually runs and the served attachment is updated. The
        spy only confirms the call path is wired; the assertIn below is the real
        behavioral proof.
        """
        from unittest.mock import patch
        color = self.env["theme.compassion.colors"].search([], limit=1)
        sentinel = "#0a0b0c"  # distinctive value unlikely to pre-exist
        with patch.object(
            self.env.registry, "clear_cache",
            wraps=self.env.registry.clear_cache,
        ) as spy:
            color.write({"color": sentinel})
            spy.assert_called()  # (a) wiring check: clear_cache must be called
        # (b) behavioral proof: the served stylesheet reflects the new value
        self.assertIn(sentinel, self._attachment_text(self.URLS["colors"]))

    def test_url_rename_idempotent(self):
        """Calling the post-migration script twice produces the same result as
        calling it once.

        Simulates a partially-failed upgrade where the rename completed but a
        later step crashed and the migration was retried from the start.
        """
        from odoo.modules.migration import load_script

        # Create a fake attachment with the old URL that the migration should rename
        old_att = self.env["ir.attachment"].create({
            "name": "fake-old-colors.scss",
            "url": "/theme/compassion/colors.scss",
            "type": "binary",
            "raw": b"/* fake css */",
        })

        # load_script accepts an absolute path (odoo/odoo/modules/migration.py:51)
        script = load_script(
            os.path.realpath(self._migration_script_path),
            "post-migration",
        )

        # migrate() takes (cr, version)
        script.migrate(self.env.cr, "14.0.2.0.0")
        script.migrate(self.env.cr, "14.0.2.0.0")  # second call must be a no-op

        old_att.invalidate_recordset()
        self.assertEqual(old_att.url, "/theme_compassion_2025/dynamic/colors.scss")

    def test_user_added_color_survives_upgrade(self):
        """A color record created at runtime (no ir_model_data binding) is
        preserved after the post-migration script runs.

        Guards against an accidental DELETE or TRUNCATE that would wipe
        user-created color data during the upgrade.
        """
        from odoo.modules.migration import load_script

        user_color = self.env["theme.compassion.colors"].create({
            "name": "User-Added Custom Color",
            "color": "#deadbe",
        })
        user_color_id = user_color.id

        # load_script accepts an absolute path (odoo/odoo/modules/migration.py:51)
        script = load_script(
            os.path.realpath(self._migration_script_path),
            "post-migration",
        )
        # migrate() takes (cr, version)
        script.migrate(self.env.cr, "14.0.2.0.0")

        # The user-created record must still exist with the original values
        survivor = self.env["theme.compassion.colors"].browse(user_color_id)
        self.assertTrue(survivor.exists())
        self.assertEqual(survivor.color, "#deadbe")
